HTTP_METHOD_PUT = 'PUT'
HTTP_METHOD_POST = 'POST'
HTTP_METHOD_DELETE = 'DELETE'

LOG_STATUS_SUCCESS = 'Success'
LOG_STATUS_FAILED = 'Fail'
LOG_STATUS_IGNORED = 'Ignored'
LOG_STATUS_PROCESSED = 'Processed'
